const data = {
  Session: "JAN-JUL 2024",
  AllotID: [1, 5, 6, 7, 8, 9, 10, 11, 12, 13],
  Branch: [
    "MAC",
    "CSE",
    "ITIOT",
    "AIDS",
    "ITIOT",
    "AIDS",
    "MAC",
    "CSE",
    "MAC",
    "CSE",
  ],
  Subject: [1, 5, 5, 5, 2, 2, 2, 2, 4, 2],
  Email: [
    "Something@gmail.com",
    "abhikarneekhra2@gmail.com",
    "faculty@gmail.com",
    "again@gmail.com",
    "abhikarneekhra@gmail.com",
    "Something@gmail.com",
    "abhikarneekhra2@gmail.com",
    "faculty@gmail.com",
    "again@gmail.com",
    "abhikarneekhra@gmail.com",
  ],
  Room: [
    "M102",
    "SH1",
    "SH2",
    "M102",
    "SH7",
    "M102",
    "M102",
    "SH9",
    "M102",
    "M102",
  ],
  Day: [
    "MONDAY",
    "MONDAY",
    "TUESDAY",
    "THURSDAY",
    "FRIDAY",
    "FRIDAY",
    "MONDAY",
    "WEDNESDAY",
    "SATURDAY",
    "THURSDAY",
  ],
};

export default data;
